services:
  - type: web
    name: legendor-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URL
        fromDatabase:
          name: legendor-db
          property: connectionString